call code --install-extension bajdzis.vscode-twig-pack 
call code --install-extension EditorConfig.EditorConfig 
call code --install-extension Hirse.vscode-ungit 
call code --install-extension HookyQR.beautify 
call code --install-extension HvyIndustries.crane 
call code --install-extension IBM.output-colorizer 
call code --install-extension ikappas.phpcs 
call code --install-extension liuji-jim.vue 
call code --install-extension neilbrayfield.php-docblocker 
call code --install-extension redhat.vscode-yaml 
call code --install-extension robertohuertasm.vscode-icons 
call code --install-extension ronnidc.nunjucks 
call code --install-extension teabyii.ayu 
call code --install-extension whatwedo.twig 